version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - online_courses_network
    environment:
      - FLASK_SECRET_KEY=admin  # Укажите ваш секретный ключ

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: courses_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - online_courses_network

networks:
  online_courses_network:
    driver: bridge

volumes:
  db_data:
